server:
  port: 18081

spring:
  application:
    name: cc-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/comrade_crony
    username: root
    password: example
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    url: redis://127.0.0.1:6381
    #    port:
    jedis:
      pool:
        max-wait: 5000ms
        max-idle: 100
        min-idle: 10
    timeout: 10s
dubbo:
  application:
    name: cc-server
    logger: slf4j
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  type-enums-package: org.cc.server.enums

cc:
  cache:
    enable: true
  sso:
    url: http://127.0.0.1:18082
    default:
      user: 2
