dubbo:
  application:
    name: dubbo-provider
    logger: slf4j
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: root
      password: example
      authentication-database: admin
      database: cc